server:
  port: 9193
spring:
  h2:
    console:
      enabled: true
  application:
    name: payment-service
  config:
    import: configserver:http://localhost:9196
  datasource:
    url: jdbc:h2:mem:paymentdb
    username: sa
    password: param
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  zipkin:
    base-url: http://localhost:9411

logging:
  file:
    name: /Users/pmishra/learnMicroservice/oms.log

