server:
  port: 9192
spring:
  application:
    name: order-service
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 3
  h2:
    console:
      enabled: true
  config:
    import: "configserver:http://localhost:9196"
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: param
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  zipkin:
    base-url: http://localhost:9411

resilience4j:
  circuitbreaker:
    instances:
      circuitBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based

logging:
  file:
    name: /Users/pmishra/learnMicroservice/oms.log